# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser
from urllib.request import urlopen
import requests
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.link=None
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.amazon_button = QtWidgets.QPushButton(self.centralwidget)
        self.amazon_button.setGeometry(QtCore.QRect(10, 40, 131, 71))
        self.amazon_button.clicked.connect(lambda: self.button_clicked('amazon'))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.amazon_button.setFont(font)
        self.amazon_button.setObjectName("amazon_button")
        self.flipkart_button = QtWidgets.QPushButton(self.centralwidget)
        self.flipkart_button.setGeometry(QtCore.QRect(170, 40, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.flipkart_button.setFont(font)
        self.flipkart_button.setObjectName("flipkart_button")
        self.flipkart_button.clicked.connect(lambda: self.button_clicked('flipkart'))
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(350, 510, 93, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.submit_button.setFont(font)
        self.submit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.submit_button.setAutoFillBackground(True)
        self.submit_button.setObjectName("submit_button")
        self.email_line = QtWidgets.QLineEdit(self.centralwidget)
        self.email_line.setGeometry(QtCore.QRect(20, 470, 761, 31))
        self.email_line.setObjectName("email_line")
        self.link_line = QtWidgets.QLineEdit(self.centralwidget)
        self.link_line.setGeometry(QtCore.QRect(20, 390, 761, 31))
        self.link_line.setObjectName("link_line")
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(20, 440, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.link_label = QtWidgets.QLabel(self.centralwidget)
        self.link_label.setGeometry(QtCore.QRect(20, 360, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.link_label.setFont(font)
        self.link_label.setObjectName("link_label")
        self.search_line = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line.setGeometry(QtCore.QRect(20, 310, 761, 31))
        self.search_line.setObjectName("search_line")
        self.search_label = QtWidgets.QLabel(self.centralwidget)
        self.search_label.setGeometry(QtCore.QRect(20, 280, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.search_label.setFont(font)
        self.search_label.setObjectName("search_label")
        self.search_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.search_label_2.setGeometry(QtCore.QRect(10, 0, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.search_label_2.setFont(font)
        self.search_label_2.setObjectName("search_label_2")
        self.snapdeal_button = QtWidgets.QPushButton(self.centralwidget)
        self.snapdeal_button.setGeometry(QtCore.QRect(500, 40, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.snapdeal_button.setFont(font)
        self.snapdeal_button.setObjectName("snapdeal_button")
        self.snapdeal_button.clicked.connect(lambda: self.button_clicked('snapdeal'))
        self.ajio_button = QtWidgets.QPushButton(self.centralwidget)
        self.ajio_button.setGeometry(QtCore.QRect(340, 40, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ajio_button.setFont(font)
        self.ajio_button.setObjectName("ajio_button")
        self.ajio_button.clicked.connect(lambda: self.button_clicked('ajio'))
        self.myntra_button = QtWidgets.QPushButton(self.centralwidget)
        self.myntra_button.setGeometry(QtCore.QRect(660, 40, 121, 71))
        self.myntra_button.clicked.connect(lambda: self.button_clicked('myntra'))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.myntra_button.setFont(font)
        self.myntra_button.setObjectName("myntra_button")
        self.bigbasket_button = QtWidgets.QPushButton(self.centralwidget)
        self.bigbasket_button.setGeometry(QtCore.QRect(660, 160, 121, 71))
        self.bigbasket_button.clicked.connect(lambda: self.button_clicked('bigbasket'))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bigbasket_button.setFont(font)
        self.bigbasket_button.setObjectName("bigbasket_button")
        self.nykaa_button = QtWidgets.QPushButton(self.centralwidget)
        self.nykaa_button.setGeometry(QtCore.QRect(10, 160, 131, 71))
        self.nykaa_button.clicked.connect(lambda: self.button_clicked('nykaa'))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nykaa_button.setFont(font)
        self.nykaa_button.setObjectName("nykaa_button")
        self.lifestyle_button = QtWidgets.QPushButton(self.centralwidget)
        self.lifestyle_button.setGeometry(QtCore.QRect(500, 160, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lifestyle_button.setFont(font)
        self.lifestyle_button.clicked.connect(lambda: self.button_clicked('lifestyle'))
        self.lifestyle_button.setObjectName("lifestyle_button")
        self.shopclues_button = QtWidgets.QPushButton(self.centralwidget)
        self.shopclues_button.setGeometry(QtCore.QRect(340, 160, 131, 71))
        self.shopclues_button.clicked.connect(lambda: self.button_clicked('shopclues'))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shopclues_button.setFont(font)
        self.shopclues_button.setObjectName("shopclues_button")
        self.paytm_button = QtWidgets.QPushButton(self.centralwidget)
        self.paytm_button.setGeometry(QtCore.QRect(170, 160, 141, 71))
        self.paytm_button.clicked.connect(lambda: self.button_clicked('paytm'))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.paytm_button.setFont(font)
        self.paytm_button.setObjectName("paytm_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.submit_button.clicked.connect(lambda: self.button_clicked("submit"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.amazon_button.setText(_translate("MainWindow", "Amazon"))
        self.flipkart_button.setText(_translate("MainWindow", "Flipkart"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))
        self.email_label.setText(_translate("MainWindow", "EMAIL "))
        self.link_label.setText(_translate("MainWindow", "LINK"))
        self.search_label.setText(_translate("MainWindow", "SEARCH"))
        self.search_label_2.setText(_translate("MainWindow", "COPY LINK FROM SITES"))
        self.snapdeal_button.setText(_translate("MainWindow", "Snapdeal"))
        self.ajio_button.setText(_translate("MainWindow", "AJIO"))
        self.myntra_button.setText(_translate("MainWindow", "Myntra"))
        self.bigbasket_button.setText(_translate("MainWindow", "BigBasket"))
        self.nykaa_button.setText(_translate("MainWindow", "Nykaa"))
        self.lifestyle_button.setText(_translate("MainWindow", "Lifestyle"))
        self.shopclues_button.setText(_translate("MainWindow", "Shopclues"))
        self.paytm_button.setText(_translate("MainWindow", "PaytmMall"))

    def button_clicked(self,text):
        if text=='amazon':
            webbrowser.open('https://www.amazon.in/')
        if text=='flipkart':
            webbrowser.open('https://www.flipkart.com/')
        if text=='ajio':
            webbrowser.open('https://www.ajio.com/')
        if text=='bigbasket':
            webbrowser.open('https://www.bigbasket.com/')
        if text=='paytm':
            webbrowser.open('https://paytmmall.com/')
        if text=='snapdeal':
            webbrowser.open('https://www.snapdeal.com/')
        if text=='lifestyle':
            webbrowser.open('https://www.lifestylestores.com/in/en/')
        if text=='shopclues':
            webbrowser.open('https://www.shopclues.com/')
        if text=='myntra':
            webbrowser.open('https://www.myntra.com/')
        if text=='nykaa':
            webbrowser.open('https://www.nykaa.com/')
        if text=='submit':
            self.link=self.link_line.text()
            ww=0
            try:
                urlopen(self.link)
                ww=1
            except:
                print("Invalid link")

            if ww==1:
                df=pd.read_html(self.link)
                flag=False
                self.price=0
                for i in range(len(df)):
                    for col in df[i]:
                        for j in df[i][[col]]:
                            print(df[i][[col]][j])
                            if j=='Price':
                                self.price=j
                                flag=True
                                break
                        if flag:
                            break
                    if flag:
                        break
                print(self.price)
                

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
